# Generated by Django 2.2.5 on 2019-09-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='regNo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='staffId',
            field=models.IntegerField(blank=True),
        ),
    ]
