# Generated by Django 2.2.5 on 2019-09-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190927_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='academic_council',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='college_council',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='department_council',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='regNo',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='school',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='school_council',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='staffId',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='student',
        ),
    ]
