# Generated by Django 2.2.5 on 2019-09-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190927_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='academic_council',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='college_council',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='department_council',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lecturer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='regNo',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='school_council',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='staffId',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='student',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
