# Generated by Django 2.2.5 on 2019-09-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190927_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='level',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
