# Generated by Django 2.2.5 on 2019-09-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190927_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
