# Generated by Django 2.2.5 on 2019-09-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190930_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='regNo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='staffId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
