# Generated by Django 2.2.5 on 2019-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190930_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='unreads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
