# Generated by Django 2.2.5 on 2019-10-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_myuser_unreads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='level',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
