# Generated by Django 2.2.5 on 2019-10-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191022_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_council',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='college_council',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department_council',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturer_category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='academic_council',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='college_council',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='department_council',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lecturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='school_council',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='student',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='school_council',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student_category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
