# Generated by Django 2.2.5 on 2019-09-27 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0003_auto_20190928_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
