# Generated by Django 2.2.5 on 2019-09-30 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announce', '0004_auto_20190928_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announce',
            old_name='creator',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='announce',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
