# Generated by Django 2.2.5 on 2019-09-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0005_auto_20190930_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='receiver',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
