# Generated by Django 2.2.5 on 2019-09-30 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announce', '0006_auto_20190930_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='receiver',
        ),
        migrations.AddField(
            model_name='announce',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
