# Generated by Django 2.2.5 on 2019-09-30 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announce', '0007_auto_20190930_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='reciever',
        ),
        migrations.AddField(
            model_name='announce',
            name='receiver',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
