# Generated by Django 2.2.5 on 2019-10-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0011_auto_20191001_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
