# Generated by Django 2.2.5 on 2019-10-03 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announce', '0012_announce_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='views',
        ),
        migrations.AddField(
            model_name='announce',
            name='view_by',
            field=models.ManyToManyField(blank=True, related_name='_announce_view_by_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
