# Generated by Django 2.2.5 on 2019-10-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0013_auto_20191003_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
