# Generated by Django 2.2.6 on 2019-10-29 14:50

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0015_auto_20191025_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
