# Generated by Django 2.2.6 on 2019-10-29 20:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0016_auto_20191029_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
