# Generated by Django 2.2.6 on 2019-10-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0017_auto_20191029_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
